### ISSUE TITLE
App crashes after log in

### ISSUE THREAD

**Issue by e-alfred** [lenchan139/NCBookmark#1]
Hello,

the app crashes after I enter the login data and the bookmarks should be loaded. Only a white screen shows up for a second an then it crashes.

My data:

Phone: BQ M5
Android version: 6.0.1
Nextcloud version: 12.0.0
Bookmarks app:  0.10.0

I sent a report using the Google play store app.

**Comment by lenchan139** [comment]
Hello, it seem bookmark app have new api and remove older one.
I will update it asap but you may use older version nextcloud bookmark as temporary solusion

would you work with old bookmark app ?

**Comment by e-alfred** [comment]
Well, this is quite a problem because 0.10.0 is the official release for Nextcloud 12 and they also worked on an API that is more stable:

https://github.com/nextcloud/bookmarks#rest-api

**Comment by lenchan139** [comment]
ok, i will code it asap.

**Comment by lenchan139** [comment]
api v2 support is done. Play store may take a few time to push the update.
If have any problem for new version, open new issue :)

**Comment by e-alfred** [comment]
Hello,

thanks for the awesome work. The only thing I found is that it shows only one screen full of bookmarks in the !undefined view (a lot of them without any tags at all). Aside from that it works very well. Do you mind to ask the Nextcloud bookmarks app developers to link your app on their Github page? It is such a useful addition to it after all.

**Comment by lenchan139** [comment]
Would you need multi-page? Pagination Support may work very later #4 
> Do you mind to ask the Nextcloud bookmarks app developers to link your app on their Github page? It is such a useful addition to it after all.
I am shy and lazy, so this mission pass to you :(

And please don't leave comment in closed issue. plz /_\
