### ISSUE TITLE
!ungrouped has no entries

### ISSUE THREAD

**Issue by 4oo4** [lenchan139/NCBookmark#12]
I was going to use the app today to organize some entries, but when I go under the !ungrouped tag I don't see any of my untagged entries.

Android: 7.1.2
Nexcloud: 12.0

**Comment by lenchan139** [comment]
it seem something was changed in last bookmark app (0.10.1) ... is you are using this version?

**Comment by lenchan139** [comment]
latest version(v7) was out, try it. If still have any problem, re-open a issue :)

**Comment by 4oo4** [comment]
@lechan139 Just downloaded and that fixed it. Thanks for the quick response!
