### ISSUE TITLE
App crash instantly after clicking on Save 

### ISSUE THREAD

**Issue by julimaster** [lenchan139/NCBookmark#15]
#### Expected behavior
App should keep working after clicking on save.

#### Actual behavior
App crash and exist its self after  clicking on save.

#### How to reproduce
1. Open the app
2. Input URL
3. Input username 
4.  Input password
5. Then click save app will crash instantly.

***
* Browser/App version: NC Bookmark Viewer version 2.3
* Operating system: Android marshmallow  6.0 ,tecno w3
***
#### Recording Of The Bug
![videotogif_2018.05.29_09.16.13.gif](https://cdn.steemitimages.com/DQmc1ne13zyR8bBKGxujvMQzMuppyhocd7Ay45Typx4F3JV/videotogif_2018.05.29_09.16.13.gif)

**Comment by lenchan139** [comment]
did you try add prefix http:// or https:// ?
