### ISSUE TITLE
Bookmarks with multiple tags don't work

### ISSUE THREAD

**Issue by DatGizmo** [lenchan139/NCBookmark#3]
Hi,
I have several bookmarks with multiple tags on them.

For example "Linux" and "QT5"
In the "NC Bookmark Tags" view this results in an list entry like this 'Linux","QT5' and the list underneath is empty.

Also I list with only on tag, I see max 10 bookmarks even if there are more with the same tag.

Gizmo

**Comment by lenchan139** [comment]
Got it. But this issue may take a long time because I got a summer job last week :(

**Comment by e-alfred** [comment]
> Also I list with only on tag, I see max 10 bookmarks even if there are more with the same tag.

I also experience this problem. I think scrolling through all bookmarks would be good enough.

**Comment by lenchan139** [comment]
>Also I list with only on tag, I see max 10 bookmarks even if there are more with the same tag.
It may be solved by #5 .

**Comment by lenchan139** [comment]
latest version (v5) is supporting multiple tags in a very stupid way.
example:
> tag1, tag2, tag3 ...

If there have any suggestion or find bugs, please open new issue and let me easy to tracking, thank you so much :)

**Comment by DatGizmo** [comment]
Multi tags are no working as expected.
Thank you very much :)

**Comment by lenchan139** [comment]
is the app(v5, play store ver suggested), nextcloud(11.0.3) and bookmark app(0.10.0) up-to-date?

**Comment by DatGizmo** [comment]
Im am running:
NC Bookmarks: v5
Nextcloud: 12.0.0
Bookmark app: 0.10.0

Problem is fixed :)

**Comment by lenchan139** [comment]
ok, perhaps I cloud close this issue?
