### ISSUE TITLE
F-Droid submission

### ISSUE THREAD

**Issue by 9662** [lenchan139/NCBookmark#7]
Hello! Many thanks for having written this very handy app.

How would you feel about adding it to the [F-Droid](https://f-droid.org/) repo?

Your application may be added by [creating a new issue in GitLab](https://gitlab.com/fdroid/rfp/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D= "New request for packaging"), or I can do it for you if you prefer.

**Comment by lenchan139** [comment]
yep, I am still busy, So hope you can do it and I will thank you  so much. :)
